### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by kevin662812** [distiny-cool/SecKill#2]
新人，请问一下运行提示
D:\sec>python main.py
Traceback (most recent call last):
  File "D:\sec\main.py", line 296, in <module>
    myDlg = MainDialog()
  File "D:\sec\main.py", line 31, in __init__
    self.move((self.screen.width() - size.width() - 80), (self.screen.height() - size.height()) / 2)
TypeError: arguments did not match any overloaded call:
  move(self, QPoint): argument 1 has unexpected type 'int'
  move(self, int, int): argument 2 has unexpected type 'float'
没接触过编程，您说的语言环境我都用pip安装了。pycharm和idle 都无法运行呢。

**Comment by kody-black** [comment]
你试试改成self.move((self.screen.width() - size.width() - 80), int((self.screen.height() - size.height()) / 2))
如果还不行就删掉这句，没多大影响

**Comment by kevin662812** [comment]
好的，谢谢大神指导，我试试
